# Generated by Django 3.0.6 on 2020-06-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='id',
        ),
        migrations.AddField(
            model_name='lobby',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='num_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player_eight',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player_five',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player_four',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player_one',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player_seven',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player_six',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player_three',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player_two',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='room_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
