# Generated by Django 3.0.6 on 2020-06-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200604_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='player_nine',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lobby',
            name='player_ten',
            field=models.CharField(default='', max_length=100),
        ),
    ]
