# Generated by Django 3.0.6 on 2020-06-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200613_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='fascist_one',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lobby',
            name='fascist_three',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lobby',
            name='fascist_two',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lobby',
            name='hitler',
            field=models.CharField(default='', max_length=100),
        ),
    ]
