# Generated by Django 3.0.6 on 2020-06-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200618_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='deck',
            field=models.CharField(default='FFFFFFFFFFFLLLLLL', max_length=17),
        ),
        migrations.AddField(
            model_name='lobby',
            name='discards',
            field=models.CharField(default='', max_length=17),
        ),
    ]
