# Generated by Django 3.0.6 on 2020-06-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200619_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='chancellor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lobby',
            name='president',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lobby',
            name='president_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobby',
            name='previous_chancellor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lobby',
            name='previous_president',
            field=models.CharField(default='', max_length=100),
        ),
    ]
