# Generated by Django 3.0.6 on 2020-06-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200619_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='ready',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lobby',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
