# Generated by Django 3.0.6 on 2020-06-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200619_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='fascist_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobby',
            name='held_cards',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='lobby',
            name='liberal_count',
            field=models.IntegerField(default=0),
        ),
    ]
