# Generated by Django 3.0.6 on 2020-06-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_lobby_hidden_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='failed_governments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobby',
            name='veto_done',
            field=models.BooleanField(default=False),
        ),
    ]
